javax:
    sql:
        DataSource:
            orders-db:
                dataSourceClassName: com.mysql.cj.jdbc.MysqlDataSource
                dataSource:
                    serverName: orders-db
                    port: 3306
                    databaseName: orders
                    user: orders
                    password: pass
